### PR TITLE
#15 - fix Add Labels to catalog and color the labels

### LINKED ISSUE #15: Add Labels to catalog and color the labels

### PR DESCRIPTION
**Pull request by wsalazag21729**
fix #15

### CODE REVIEW

File: src/components/gameCard/gameCard.js [hunk 1]
```diff
@@ -38,10 +41,28 @@ class GameCard extends Component {
         img.src = src;
     }
 
+    loadLabelTag() {
+        const { idGame, gamesInformation } = this.props;
+        const gameLabelsData = gamesInformation.get('gamesLabels').filter(gameLabel => idGame === gameLabel.game_id);
+        const labelsArrayData = gameLabelsData.map(gameLabel => gamesInformation.get('labels').find(label => label.id === gameLabel.label_id));
+
+        console.log('labelsArrayData', labelsArrayData);
```
Comment (johnandresmedina) [inline src/components/gameCard/gameCard.js]: can you please delete this

**Review by johnandresmedina — CHANGES_REQUESTED** [review]

**Comment by filgaia** [comment]
The commit should say fix to close the issue

File: src/components/catalog/catalog.js [hunk 2]
```diff
@@ -33,10 +33,12 @@ class Catalog extends Component {
                 <Grid item key={get(card, 'id')} xs={12} sm={6} md={4} lg={3}>
                     <LazyLoad height={250}>
                         <GameCard
+                            idGame={get(card, 'id', '')}
```
Comment (filgaia) [inline src/components/catalog/catalog.js]: Id Is not a number? The empty string i think Is not needed

File: src/components/gameCard/gameCard.js [hunk 3]
```diff
@@ -38,10 +41,28 @@ class GameCard extends Component {
         img.src = src;
     }
 
+    loadLabelTag() {
+        const { idGame, gamesInformation } = this.props;
+        const gameLabelsData = gamesInformation.get('gamesLabels').filter(gameLabel => idGame === gameLabel.game_id);
```
Comment (filgaia) [inline src/components/gameCard/gameCard.js]: I suggest move the list of labels for each game to the action fill. This Will help us for filtering

File: src/components/gameCard/gameCard.js [hunk 4]
```diff
@@ -38,10 +41,28 @@ class GameCard extends Component {
...
+        const labelsArrayData = gameLabelsData.map(gameLabel => gamesInformation.get('labels').find(label => label.id === gameLabel.label_id));
+
+        console.log('labelsArrayData', labelsArrayData);
+        return labelsArrayData.groupBy(label => label.id).map(x => x.first()).toList().map(label => {
+
```
Comment (filgaia) [inline src/components/gameCard/gameCard.js:48]: Delete too much empty space

File: src/reducers/gamesInformation.js [hunk 5]
```diff
@@ -10,18 +10,24 @@ const setInitialState = () => Immutable.fromJS({
...
 
 const gameInformationReducer = handleActions(
     {
         [actions.loadJsonInformation]: (state, action) =>
-            state.merge({
+            state.mergeDeep({
                 loading: false,
-                source: get(action, 'payload.response.games', [])
+                source: get(action, 'payload.response.games', []),
+                gamesLabels: get(action, 'payload.response.gamesLabels', []),
```
Comment (filgaia) [inline src/reducers/gamesInformation.js]: If we move the labels we dont need this map

File: src/reducers/gamesInformation.js [hunk 6]
```diff
@@ -10,18 +10,24 @@ const setInitialState = () => Immutable.fromJS({
...
+    labels: [],
+    platforms: [],
     hasMoreItems: true
 });
 
 const gameInformationReducer = handleActions(
     {
         [actions.loadJsonInformation]: (state, action) =>
-            state.merge({
+            state.mergeDeep({
```
Comment (filgaia) [inline src/reducers/gamesInformation.js]: Why change all for mergeDeep? Are you sure Is necesary

**Review by filgaia — CHANGES_REQUESTED** [review]

File: src/reducers/gamesInformation.js (hunk 6 above)
Comment (wsalazag21729) [reply src/reducers/gamesInformation.js]: I think we need `mergeDeep` because is necesary that all the objects in games array becames in immutable objects, but with all changes I remove Deep because with `merge` and `mergeDeep` the app has the same behaviour

File: src/components/gameCard/gameCard.js [hunk 7]
```diff
@@ -32,16 +37,30 @@ class GameCard extends Component {
 
     checkImage(src) {
         var img = new Image();
-        const imageSrc = 'data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22288%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20288%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164edaf95ee%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164edaf95ee%22%3E%3Crect%20width%3D%22288%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2296.32500076293945%22%20y%3D%22118.8%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E'; // eslint-disable-line max-len
+        const imageSrc = ERROR_IMAGE; // eslint-disable-line max-len
```
Comment (filgaia) [inline src/components/gameCard/gameCard.js]: The eslint comment can be removed

File: src/constants/index.js [hunk 8]
```diff
@@ -0,0 +1,7 @@
+const ITEMS_BY_PAGE = 20;
+const ERROR_IMAGE = 'data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22288%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20288%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164edaf95ee%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164edaf95ee%22%3E%3Crect%20width%3D%22288%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2296.32500076293945%22%20y%3D%22118.8%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E';
```
Comment (filgaia) [inline src/constants/index.js]: Missing eslint comment?

File: src/reducers/gamesInformation.js [hunk 9]
```diff
@@ -31,7 +33,7 @@ const gameInformationReducer = handleActions(
                 loading: true
             }),
         [actions.shortGamesByNameSuccess]: (state, action) =>
-            state.merge({
+            state.mergeDeep({
```
Comment (filgaia) [inline src/reducers/gamesInformation.js]: MergeDeep needed?

**Review by filgaia — CHANGES_REQUESTED** [review]

**Review by filgaia — APPROVED** [review]

**Review by johnandresmedina — APPROVED** [review]
